{"result":[
	<rows>
	{
		"tuid":"${fld:tuid}"
		,"area_id":"${fld:area_id}"
		,"name":"${fld:name@js}"
		,"device_model":"${fld:device_model}"
		,"machine_no":"${fld:machine_no}"
		,"check_status":"${fld:check_status}"
		,"repair_by":"${fld:repair_by}"
		,"telephone":"${fld:telephone}"
        ,"unit_name":"${fld:unit_name}"
		,"repaird":"${fld:repaird}"
	},
	</rows>
	{}
]}