{"result":[
	<rows>
	{
		"tuid":"${fld:tuid}"
		,"area_id":"${fld:area_id}"
		,"name":"${fld:name@js}"
		,"device_model":"${fld:device_model}"
		,"machine_no":"${fld:machine_no}"
	},
	</rows>
	{}
]}