document.formEditor.tuid.value = "${fld:tuid}";
document.formEditor.name.value = "${fld:name@js}";
document.formEditor.sn.value = "${fld:sn@js}";
document.formEditor.pn.value = "${fld:pn@js}";
document.formEditor.purchase_contract.value = "${fld:purchase_contract@js}";
document.formEditor.transfer_record.value = "${fld:transfer_record@js}";
document.formEditor.airport_sign.value = "${fld:airport_sign@js}";
document.formEditor.maintain_sign.value = "${fld:maintain_sign@js}";
document.formEditor.remark.value = "${fld:remark@js}";
document.formEditor.device_id.value = "${fld:device_id}";
document.formEditor.device_name.value = "${fld:device_name@js}";
setCheckboxValue("new_sign","${fld:new_sign}","formEditor");