{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"tuid":"${fld:tuid}",
		"term_name":"${fld:term_name@js}",
		"term_type":"${fld:term_type@js}",
		"remark":"${fld:remark@js}",
		"status":"${fld:status@js}"
	},
	</rows>
	{}
]}